spring:
  application:
    # 应用名称
    name: ruoyi-auth
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        # 服务注册地址
        username: nacos  # 用户名
        password: nacos  # 密码
        namespace: public  # 命名空间（默认）
      config:
        # 配置中心地址
        server-addr: http://localhost:8848
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

